name: LibYAML Generator

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"

      - name: Install Dependencies
        run: julia --project=gen -e 'using Pkg; Pkg.instantiate()'

      - name: Build Artifacts
        id: build
        run: julia --project=gen gen/generator.jl

      - run: git status
      - run: git diff --color

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Update generated Julia wrapper files"
          body: "This is an automated pull request to update the generated wrapper files."
